#!/usr/bin/env perl
#
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
#
# Licensed under the terms of the GNU GPL v3, or any later version.
#
# This script is meant to use with i3blocks. It parses the output of the "acpi"
# command (often provided by a package of the same name) to read the status of
# the battery, and eventually its remaining time (to full charge or discharge).
#
# The color will gradually change for a percentage below 85%, and the urgency
# (exit code 33) is set if there is less that 5% remaining.

use strict;
use warnings;
use utf8;

my $acpi;
my $status;
my $percent;
my $ac_adapt;
my $full_text;
my $short_text;
my $bat_number = $ENV{BAT_NUMBER};
if (not defined($bat_number) or $bat_number eq '') {
    if (opendir(my $dh, "/sys/class/power_supply")) {
        my @bats = grep {
            my $f = "/sys/class/power_supply/$_/type";
            -f $f && do {
                open my $fh, "<", $f;
                my $t = <$fh>;
                close $fh;
                chomp($t);
                $t eq "Battery"
            }
        } readdir($dh);
        closedir($dh);
        @bats = sort @bats;
        for (my $i = 0; $i < @bats; $i++) {
            if ($bats[$i] =~ /^BAT\d+$/) {
                $bat_number = $i;
                last;
            }
        }
    }
    $bat_number //= 0;
}
my $label = $ENV{LABEL} || "";

# Read all lines of the "acpi" command output
open (ACPI, "acpi -b 2>/dev/null |") or die;
my @lines = <ACPI>;
close(ACPI);

# Automatically find a battery that has charge, or fallback to the first parsed line
foreach my $line (@lines) {
    if ($line =~ /Battery (\d+): ([\w\s]+), (\d+)%/) {
        my $percent = $3;
        if ($percent > 0 || not defined($acpi)) {
            $acpi = $line;
            if ($percent > 0) {
                last;
            }
        }
    }
}

# If no batteries matched the pattern, default to the first line if available
if (not defined($acpi) and @lines > 0) {
    $acpi = $lines[0];
}

# fail on unexpected output
if (not defined($acpi)) {
    # don't print anything to stderr if there is no battery
    exit(0);
}
elsif ($acpi !~ /: ([\w\s]+), (\d+)%/) {
	die "$acpi\n";
}

$status = $1;
$percent = $2;

my $icon = '';
if ($percent < 15) {
    $icon = '';
} elsif ($percent < 40) {
    $icon = '';
} elsif ($percent < 65) {
    $icon = '';
} elsif ($percent < 85) {
    $icon = '';
}

my $charge_symbol = '';
if ($status eq 'Charging') {
    $charge_symbol = ' ';
}

$full_text = "$charge_symbol$icon  $percent%";

if ($status eq 'Unknown') {
	open (AC_ADAPTER, "acpi -a |") or die;
	$ac_adapt = <AC_ADAPTER>;
	close(AC_ADAPTER);

	if ($ac_adapt =~ /: ([\w-]+)/) {
		$ac_adapt = $1;

		if ($ac_adapt eq 'on-line') {
			$charge_symbol = ' ';
            $full_text = "$charge_symbol$icon  $percent%";
		}
	}
}

$short_text = $full_text;

if ($acpi =~ /(\d\d:\d\d):/) {
	$full_text .= " ($1)";
}

# print text
print "$full_text\n";
print "$short_text\n";

# consider color and urgent flag only on discharge
if ($status eq 'Discharging') {

	if ($percent < 20) {
		print "#FF0000\n";
	} elsif ($percent < 40) {
		print "#FFAE00\n";
	} elsif ($percent < 60) {
		print "#FFF600\n";
	} elsif ($percent < 85) {
		print "#A8FF00\n";
	}

	if ($percent < 5) {
		exit(33);
	}
}

exit(0);
