#!/usr/bin/env bash

# Toggle mic if clicked
if [ -n "$BLOCK_BUTTON" ] && [ "$BLOCK_BUTTON" -eq 1 ]; then
    wpctl set-mute @DEFAULT_SOURCE@ toggle
    
    # Send a notification
    status=$(wpctl get-volume @DEFAULT_SOURCE@)
    if echo "$status" | grep -q "\[MUTED\]"; then
        dunstify -h string:x-dunst-stack-tag:mic "Microphone" "Muted"
    else
        dunstify -h string:x-dunst-stack-tag:mic "Microphone" "Active"
    fi
fi

# Get current status for status line
status=$(wpctl get-volume @DEFAULT_SOURCE@)
if echo "$status" | grep -q "\[MUTED\]"; then
    echo "🎤🔴"
else
    echo "🎤🟢"
fi
