#!/usr/bin/env bash

# If clicked, launch the rofi power menu in the background
if [ -n "$BLOCK_BUTTON" ]; then
    rofi -show power-menu -modi power-menu:/home/pottarr/.config/i3/power_menu.sh &
fi

echo "⏻"
