-- return {
--   "stevearc/conform.nvim",
--   opts = {
--     formatters = {
--       stylua = {
--         prepend_args = { "--indent-type", "Spaces", "--indent-width", "4" },
--       },
--     },
--     formatters_by_ft = {
--       lua = { "stylua" },
--       rust = { "rustfmt" },
--     },
--   },
-- }

-- local null_ls = require("null-ls")
--
-- null_ls.setup({
--   sources = {
--     -- formatters
--     null_ls.builtins.formatting.prettier,
--     null_ls.builtins.formatting.black,
--     null_ls.builtins.formatting.clang_format,
--     null_ls.builtins.formatting.shfmt,
--     null_ls.builtins.formatting.stylua,
--     null_ls.builtins.formatting.nixpkgs_fmt,
--     -- You can add diagnostics too if needed
--   },
-- })
--
