typeset -U path cdpath fpath manpath
for profile in ${(z)NIX_PROFILES}; do
  fpath+=($profile/share/zsh/site-functions $profile/share/zsh/$ZSH_VERSION/functions $profile/share/zsh/vendor-completions)
done

HELPDIR="/nix/store/q02m3zz38942iyji3flncapak4m6sahh-zsh-5.9/share/zsh/$ZSH_VERSION/help"

# oh-my-zsh extra settings for plugins

# oh-my-zsh configuration generated by NixOS
plugins=(git)


source $ZSH/oh-my-zsh.sh

# History options should be set in .zshrc and after oh-my-zsh sourcing.
# See https://github.com/nix-community/home-manager/issues/177.
HISTSIZE="10000"
SAVEHIST="10000"

HISTFILE="$HOME/.zsh_history"
mkdir -p "$(dirname "$HISTFILE")"

setopt HIST_FCNTL_LOCK
unsetopt APPEND_HISTORY
setopt HIST_IGNORE_DUPS
unsetopt HIST_IGNORE_ALL_DUPS
unsetopt HIST_SAVE_NO_DUPS
unsetopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_SPACE
unsetopt HIST_EXPIRE_DUPS_FIRST
setopt SHARE_HISTORY
unsetopt EXTENDED_HISTORY

export WINIT_X11_SCALE_FACTOR=1
export WINIT_UNIX_BACKEND="x11"
export EDITOR="nvim"
export VISUAL="nvim"
export MANPAGER='nvim +Man!'

export PATH="$HOME/.local/bin:$PATH"

alias cd="z"
alias ls="eza --icons=always"
alias tree="eza -T --icons=always"
alias za="zathura"
alias open="xdg-open"
alias cdd="zi"

export SKIM_DEFAULT_OPTIONS="--color=fg:#e4e4ef,bg:#181818,fg+:#f4f4ff,bg+:#282828,pointer:#ffdd33 --reverse --prompt='-> '"
autoload -U colors && colors
# NIXOS_LOGO="U+F302"
# PROMPT="${NIXOS_LOGO} %F{cyan}%~%f %# "

# PROMPT='%F{76}%n@%m%f:%F{220}%~%f %F{188}→%f '
# PROMPT='%F{76}%~%f $(git_prompt_info) %F{188}→%f '
# Enable OMZ git plugin in your .zshrc
# plugins=(git)

# Prompt definition
PROMPT='%F{76}%n@%m%f:%F{220}%~%f $(git_prompt_info) %F{231}→%f '
ZSH_THEME_GIT_PROMPT_PREFIX="%F{188}("    # before branch
ZSH_THEME_GIT_PROMPT_SUFFIX=")%f"           # after branch
ZSH_THEME_GIT_PROMPT_DIRTY="%F{124}✗%f"     # repo dirty
ZSH_THEME_GIT_PROMPT_CLEAN="%F{76}✓%f"   # repo clean
